## <center> `NumPy Tutorial` 
#### <center>  Notes from IIT-KGP course and Official documentation

##### Basic Introduction
- What is NumPy:
  - NumPy is a library that supports large, multi-dimensional arrays and matrices.
  - It has large collection of high-level mathematical functions to operate on these arrays. <br>

- Why use NumPy?
  - Although lists serve the purpose of arrays, they are slow to process.
  - NumPy is 50% faster than traditional Python lists.
  - Array object in NumPy is called ` ndarray `
  - Arrays are frequently used in data science where speed and resources are important. <br>

- Why is NumPy faster than Lists?
  - NumPy arrays are stored at one continous place in memory unlike lists, thus processes can access & manipulate them very efficiently. (*Concept: locality of reference*)
  - NumPy is also optimized to work with latest CPU architectures

#### What is an "Array"
- An array is a structure for storing & retrieving data.
- Often, we imagine array as if it were a ` grid in space `, where each cell stores one element of data.
- if a element is a number, it is a one-dimensional array (1-D array)
- a two-dimensional array (2-D array) will look like a table stacked on each other, and so on.<br> <br>

#### Restrictions regardign NumPy arrays
- All elements of the array must of be same datatype
- Once created, the ` total-size ` of the array cannot be changed.
- The shape must be rectangular & not jagged (e.g.: each row of a 2D array must have the same number of columns)
- We can use remember characteristics to actually use NumPy more properly

 

### ` Working with NumPy `

In [1]:
# importing NumPy array: the first compulsory step

import numpy as np # np is the standard aliasing

#### ` 01. Array Creation `

6 - general mechanisms for creating arrays: 
1. Conversion from other Python structures (*from lists & tuples*)
2. Intrinsic NumPy creation functions (*.arange, ones, zeros etc.*)
3. Replicating, Joining or Mutating existing arrays
4. Reading arrays from disk, either from standard or custom formats
5. Creating arrays from raw-bytes through the use of strings or buffers
6. Use of special libraries (like *random*)

##### *i. Converting Python sequences to NumPy arrays*
Lists & tuples can define ndarray creation
  - a list of numbers will create a 1D-array
  - a list of lists will create a 2D-array
  - further nested lists will create higher-dimensional arrays.

In [10]:
# creating lists

lst1 = [1, 2]
lst2 = [3, 4]

# 1D array
a1D = np.array(lst1)
print("This is One-Dimensional array: ", a1D)

print("- - - - -")

# 2D array
a2D = np.array([lst1, lst2])    # Remember the square brackets, they are important
print("This is Two-Dimensional array:\n ", a2D)

print("- - - - -")

# 3D array
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("This is a Three-Dimensional array:\n ", a3D)

This is One-Dimensional array:  [1 2]
- - - - -
This is Two-Dimensional array:
  [[1 2]
 [3 4]]
- - - - -
This is a Three-Dimensional array:
  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#### *ii. Intrinsic NumPy array creation functions*
- There are over 40 built-in functions to create arrays in NumPy
- These functions can be split into 3-categories roughly, based on the dimension of the array they create
  - 1D arrays
  - 2D arrays
  - ndarrays

` 1D array creation function `

- **np.arange** and **np.linspace** are important 1D array creation function.
- They generally need atleast 2-inputs (start, stop)

In [11]:
# np.arange

# np.arange creates arrays with regularly incrementing values
# best practice: np.arange(start, stop, step), dtype is optional
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2, 10, dtype = float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [13]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

In [14]:
# np.linspace

# np.linspace will create arrays with a specified number of elements spaced equally between start and stop values

np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

` 2D array creation function `

- **np.eye** and **np.diag** and **np.vander** are important 2D array creation function.


In [15]:
# np.eye(n, m)
# defines 2D matrix
# the row where i = j (row index = column index), are 1, rest are 0

np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
np.eye(3, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [17]:
# np.diag
# can either define a square 2D array with given values along diagonal, OR
# if a given 2D array returns a 1D array, that is only the diagonal elements
# helpful while doing linear algebra

np.diag([1, 2, 3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [18]:
np.diag([1, 2, 3], 1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

In [19]:
np.diag([[1, 2], [3, 4]])

array([1, 4])

In [20]:
# vander(x, n)
# defines a Vandermonde matrix as a 2D NumPy array.
# helpful in generating linear least squares model

np.vander(np.linspace(0, 2, 5), 2)

array([[0. , 1. ],
       [0.5, 1. ],
       [1. , 1. ],
       [1.5, 1. ],
       [2. , 1. ]])

In [21]:
np.vander([1, 2, 3, 4], 2)

array([[1, 1],
       [2, 1],
       [3, 1],
       [4, 1]])

In [22]:
np.vander((1, 2, 3, 4), 4)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

` General ndarray creation function `

- **np.ones** and **np.zeros** and **random** define arrays based upon the desired shape


In [24]:
# np.zeros
# creates an array filled with 0 values with the specified shape
# default dtype is float64

np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [26]:
# np.ones
# will create an array filled with 1 values.
# identical to zeros in all other respects 

np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [27]:
np.ones((2, 3, 2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [28]:
# random method of default_rng
# creates an array filled with random values between 0 & 1

from numpy.random import default_rng  # import

default_rng(42).random((2,3))

array([[0.77395605, 0.43887844, 0.85859792],
       [0.69736803, 0.09417735, 0.97562235]])

In [29]:
default_rng(42).random((2,3,2))

array([[[0.77395605, 0.43887844],
        [0.85859792, 0.69736803],
        [0.09417735, 0.97562235]],

       [[0.7611397 , 0.78606431],
        [0.12811363, 0.45038594],
        [0.37079802, 0.92676499]]])

In [30]:
# np.indices
# will create a set of arrays (stacked as a one-higher dimensioned array)
# one per dimension with each representing variation in that dimension
# helpful for evaluating functions of multiple dimensions on a regular grid

np.indices((3, 3))

array([[[0, 0, 0],
        [1, 1, 1],
        [2, 2, 2]],

       [[0, 1, 2],
        [0, 1, 2],
        [0, 1, 2]]])

##### *i. Replicating, Joining OR Mutating existing arrays*
to create new arrays.

- When you assign an array or its elements to a new variable, you have to explicitly ` np.copy ` the array, otherwise the variable is a view into the original array.

In [35]:
a = np.array([1, 2, 3, 4])
print("a: ", a)

b = a[:2].copy()
print("b: ", b)

print("- - - - -")
print("- - - - -")

b += 1
print('a = ', a, '\nb = ', b)

a:  [1 2 3 4]
b:  [1 2]
- - - - -
- - - - -
a =  [1 2 3 4] 
b =  [2 3]
